spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: mailDetails:org.ilia.mailschedulerservice.entity.MailDetails

keycloak:
  email: ${KEYCLOAK_ADMIN_EMAIL}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

cron.send-appointment-reminder-email: 0 0 8 * * *

eureka:
  instance.prefer-ip-address: true
  client.service-url.defaultZone: http://eureka:8002/eureka/