spring:
  security.oauth2.resourceserver.opaquetoken:
    introspection-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect
    client-id: ${keycloak.client-id}
    client-secret: ${keycloak.client-secret}

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: mailDetails:org.ilia.userservice.entity.MailDetails

keycloak:
  server-url: http://keycloak:8001
  realm: dental-clinic-realm
  email: ${KEYCLOAK_ADMIN_EMAIL}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  client-id: dental-clinic-client
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  instance.prefer-ip-address: true
  client.service-url.defaultZone: http://eureka:8002/eureka/

server.port: 8010

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always